### ISSUE TITLE
Adding threads error

### ISSUE THREAD

**Issue by toppark** [VirtusLab-Open-Source/strapi-plugin-comments#288]
When attempting to post a reply to an existing comment, I get the following errors;

###When threadOf is a string
```
{
  "author": {
    "id": 33,
    "name": "heehah",
    "email": "tuser@email.com"
  },
  "content": "Is this a real reply?",
  "threadOf" : "2"
}

----------------------------------------------------
{
  "data": null,
  "error": {
    "status": 400,
    "name": "Strapi:Plugin:Comments",
    "message": "Thread does not exist"
  }
}

```

###When threadOf is a number

```
{
  "data": null,
  "error": {
    "status": 400,
    "name": "BadRequestError",
    "message": "{\"name\":\"Strapi:Plugin:Comments\",\"status\":400,\"message\":\"Path: threadOf Code: invalid_type Message: Expected string, received number\"}"
  }
}
```

**Comment by Kronos66** [comment]
Hi @toppark, thank you for the reporting this issue, but we got similar [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/285#issuecomment-2592263538) and resolved in this [MR](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/pull/287)

**Comment by toppark** [comment]
> Hi @toppark, thank you for the reporting this issue, but we got similar [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/285#issuecomment-2592263538) and resolved in this [MR](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/pull/287)

Thanks for the response, but I get an error for entering both a number or string in threadOf.

**Comment by Kronos66** [comment]
Hi,
- In the first case, you received an error indicating that the thread does not exist. Please check your site, as I can't fix this.
- In the second case, you encountered an error linked to the app plugin logic, which I resolved in the mentioned MR.

**Comment by toppark** [comment]
> Hi,
> 
> * In the first case, you received an error indicating that the thread does not exist. Please check your site, as I can't fix this.
> * In the second case, you encountered an error linked to the app plugin logic, which I resolved in the mentioned MR.

Alright maybe I'm missing something beacuse I think I'm following the docs right. A GET request to `http://localhost:1337/api/comments/api::article.article:kmr4bvnzpuimr3saa1m9r3z9` returns 

```
[
  {
    "id": 1,
    "documentId": "lws4visay4j2bamiqmr0ggwi",
    "content": "This is my first commment, I'm trying to wrap my head around this plugin.",
    "blocked": false,
    "blockedThread": false,
    "blockReason": null,
    "isAdminComment": null,
    "removed": null,
    "approvalStatus": "APPROVED",
    "createdAt": "2025-01-03T06:11:39.670Z",
    "updatedAt": "2025-01-15T03:55:47.999Z",
    "publishedAt": "2025-01-03T06:11:39.671Z",
    "locale": null,
    "reports": [],
    "gotThread": true,
    "threadFirstItemId": 7,
    "author": {
      "id": "1",
      "name": "heehah",
      "email": "randmon@email.com",
      "avatar": null
    },
    "children": [
      {
        "id": 7, 
        "documentId": "mvc35ffflwz39dellcb64stt",
        "content": "Adding a reply",
        "blocked": false,
        "blockedThread": false,
        "blockReason": null,
        "isAdminComment": true,
        "removed": null,
        "approvalStatus": null,
        "createdAt": "2025-01-15T03:56:07.689Z",
        "updatedAt": "2025-01-15T04:46:58.286Z",
        "publishedAt": "2025-01-15T03:56:07.699Z",
        "locale": null,
        "reports": [],
        "gotThread": false,
        "author": {
          "id": "1",
          "name": "Me",
          "email": "email@email.com",
          "avatar": null
        },
        "children": []
      }
    ]
  }
```

Is this the correct format for a POST request? :

```
{
  "author": {
    "id": 33,
    "name": "heehah",
    "email": "email@usermail.com"
  },
  "content": "Is this a real reply?",
  "threadOf" : "7" //What ID goes here?
}
``

**Comment by Kronos66** [comment]
HI @toppark in the `threadOf`, you should put the comment ID of which one is a parent in the discussion. Please keep in mind that the fix for the thread is on [MR](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/pull/287/files#diff-49bd683b077d32f588e9cbc9cb517decd8d9ad18392eca4eb13c121c9f65d801R81). Please confirm to me: do you test this fix?

**Comment by cyp3rius** [comment]
Fixed in `v3.0.4`

**Comment by toppark** [comment]
I'm certain I am doing something wrong, can you point me in the right direction, please. I still have the same error

POST request
```
{
  "content": "Is this a new real reply?",
  "threadOf": "ljpm1d6ylbxydxt2g40xrm3f",
    "author": {
    "id": 3,
    "name": "heehah",
    "email": "user@email.com"
  }
}
```

Response
```
{
  "data": null,
  "error": {
    "status": 400,
    "name": "Strapi:Plugin:Comments",
    "message": "Thread does not exist"
  }
}
```

But that comment exists, see here:

```
{
    "id": 2,
    "documentId": "ljpm1d6ylbxydxt2g40xrm3f",
    "content": "Is this a real reply?",
    "blocked": false,
    "blockedThread": false,
    "blockReason": null,
    "isAdminComment": null,
    "removed": null,
    "approvalStatus": null,
    "createdAt": "2025-01-17T06:24:45.981Z",
    "updatedAt": "2025-01-17T06:24:45.981Z",
    "publishedAt": "2025-01-17T06:24:45.981Z",
    "locale": null,
    "reports": [],
    "gotThread": false,
    "author": {
      "id": "3",
      "name": "heehah",
      "email": "test@email.com",
      "avatar": null
    },
    "children": []
  },
````

**Comment by Kronos66** [comment]
Hi, in the `threadOf` field you need put `commentId` not `documentId`, in your example you should put: `2` :)

**Comment by toppark** [comment]
> Hi, in the `threadOf` field you need put `commentId` not `documentId`, in your example you should put: `2` :). The threading by documentId is not yet supported

Sure, I've tried that and I still get the same error response.

**Comment by toppark** [comment]
> > Hi, in the `threadOf` field you need put `commentId` not `documentId`, in your example you should put: `2` :). The threading by documentId is not yet supported
> 
> Sure, I've tried that and still get the same error response.

I've found a workaround for resolving this in my local setup. When `locale` isn't set to null, `threadOF` returns null here;
```
      const threadData = await tryCatch(
        async () => {
          return threadOf ? await this.getCommonService().findOne({ id: threadOf, related: relation, locale: null }) : null;
        },
        new PluginError2(400, "Thread does not exist")
      );
```
There's also an issue with the following block where the POST request takes very long because it's trying to send a notification, I guess.

```
      const sanitizedEntity = this.getCommonService().sanitizeCommentEntity(entity, doNotPopulateAuthor);
      try {
        await this.sendResponseNotification(sanitizedEntity);
      } catch (e) {
        console.error(e);
      }
```

**Comment by Kronos66** [comment]
HI @toppark could you open new issue because looks like you find new bug related to locales, please open new issue
