### ISSUE TITLE
Unable to get populated author avatar

### ISSUE THREAD

**Issue by vitakili** [VirtusLab-Open-Source/strapi-plugin-comments#310]
Im using latest available **plugin** (3.0.9) and **Strapi** (5.12.4) version and althought Im sending "**avatar**" url in the post comment body I still got it returned as "**null**"  in the Admin panel and in the response to the client.

Im sending the requests as an authorized user and got "**avatar**" field in the "users" collection.

For now I had to create custom api route to populate the "**avatar**" field. 

`const controllers = ({ strapi }: StrapiContext) => ({
  async findAllFlat(ctx: RequestContext) {
    const commentsCommonService = strapi
      .plugin("comments")
      .controller("client");

    try {
      // Zavolejte službu s upravenými parametry
      const response = await commentsCommonService.findAllFlat(ctx);
      const data = response.data;

      // Vytvořte cache pro URL adresy avatarů
      const avatarCache = new Map<string, string | null>();

      // Mapujte data a přidejte objekt uživatele
      const enhancedData = await Promise.all(
        data.map(async (item) => {
          try {
            const authorId = item.author.id;

            // Zkontrolujte, zda je URL adresa avatara již v mezipaměti
            if (!avatarCache.has(authorId)) {
              // Načtěte uživatele a vyplňte avatara
              const user = await strapi.entityService.findOne(
                "plugin::users-permissions.user",
                authorId, // Předpokládá se, že author.id obsahuje ID uživatele
                {
                  populate: {
                    avatar: true, // Naplnit vztah avatara
                  },
                },
              );

              // Extrahuje URL avatara
              // @ts-ignore
              const avatarUrl = user?.avatar?.url || null;

              // Uložte URL avatara do mezipaměti
              avatarCache.set(authorId, avatarUrl);
            }

            // Získejte URL avatara z mezipaměti
            const avatarUrl = avatarCache.get(authorId);

            return {
              ...item,
              author: {
                ...item.author,
                avatar: avatarUrl, // Přidejte URL avatara do objektu autora
              },
              user: null, // Můžete to odstranit, pokud nepotřebujete celý objekt uživatele
            };
          } catch (error) {
            console.error("Chyba při načítání uživatele:", error);
            return {
              ...item,
              user: null, // Přidejte nulový objekt uživatele v případě chyby
            };
          }
        }),
      );

      // Vraťte vylepšená data
      ctx.body = { ...response, data: enhancedData };
    } catch (err) {
      console.error(err);
      ctx.throw(500, "Nepodařilo se načíst komentáře");
    }
  },
});`

Other problem i face is that Im unable to remove an comment. I could **update**, but not **remove**

This is the log from Strapi console for comment removal "${STRAPI_URL}api/comments/${relationId}/comment/${commentId}?authorId=${authorId}`"
"[2025-04-14 09:16:29.950] error: Entity does not exist or you're not allowed to take an action on it
Strapi:Plugin:Comments: Entity does not exist or you're not allowed to take an action on it
    at Object.markAsRemoved (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\strapi-plugin-comments\dist\server\index.js:76:29103)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.removeComment (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\strapi-plugin-comments\dist\server\index.js:76:13680)
    at async returnBodyMiddleware (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\services\server\compose-endpoint.js:46:20)
    at async policiesMiddleware (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\services\server\policy.js:21:9)
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\services\server\compose-endpoint.js:27:20
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\dist\src\middlewares\deepPopulate.js:78:9
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\middlewares\body.js:45:17
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\middlewares\powered-by.js:12:9
    at async cors (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@koa\cors\index.js:106:16)
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\middlewares\errors.js:9:13
    at async C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\@strapi\core\dist\middlewares\logger.js:6:9
    at async session (C:\Users\VITA\Nextjs\lego-zcu\strapi\node_modules\koa-session\index.js:41:7)
[2025-04-14 09:16:29.950] http: DELETE /api/comments/api::section.section:cw5o7httyp0uhkndnbm2ynbv/comment/98?authorId=42 (9 ms) 404"

**Comment by Kronos66** [comment]
Hi @vitakili , regarding your issues:

* The `plugin::users-permissions.user` model does not include an `avatar` field by default for logged-in users. You'll need to add this field via a plugin or extension patch. Please confirm if you've made this modification to your Strapi instance.
* Regarding the DELETE request, I've tested both scenarios (Strapi user and non-Strapi user), and both are working as expected:
    * For logged-in users, we use the ID from the user context.
    * For non-logged-in users, we use the ID from the query parameters.

We have a detection mechanism that prioritises the logged-in user if present. I've identified one scenario where this might not work as expected: if you are logged in and attempt to remove a comment assigned to a non-logged-in user. Even if the author ID matches, we return a 404 error because the logged-in user's priority takes precedence.

**Comment by vitakili** [comment]
Hi @Kronos66 user has "avatar" field added to the collection. I've created custom api endpoint to populate avatar images to the comments

**Comment by Yvres-Vreucheu** [comment]
I had to use a lifecycle hook to see the avatar in admin and get it in the response.

 In **src/index.ts** of your strapi project 
```
module.exports = {

  async bootstrap({ strapi }) {

    strapi.db.lifecycles.subscribe({
      models: ['plugin::comments.comment'],

      async beforeCreate(event) {
        const { data, where, select, populate } = event.params

        const user = await strapi.db
          .query('plugin::users-permissions.user')
          .findOne({
            where: { id: data.authorId },
            populate: ['avatar']
          })

        const avatar = user?.avatar?.url
        if (avatar) {
          data.authorAvatar = avatar
        }
      }
    })
  }
}
```

Hope it helps :)

**Comment by Kronos66** [comment]
Hi,
Thanks for the suggestion, but I prepared a fix here: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/pull/315, and I hope we will merge it soon, and that solution is not necessary :)

**Comment by Yvres-Vreucheu** [comment]
Hi @Kronos66 and thanks for the fix ! 
About the delete problem, i don't understand how IDs can match between two different authors in this sentence :

> if you are logged in and attempt to remove a comment assigned to a non-logged-in user. Even if the author ID matches...

I'm trying to delete one of my comment while being connected and authenticated roles permissions on the plugin have been set but i still get this 

```
{
  data: null,
  error: {
    status: 404,
    name: 'Strapi:Plugin:Comments',
    message: "Entity does not exist or you're not allowed to take an action on it"
  }
}
```

Request is :  `/api/comments/api::article.article:nketgecqwk8jsc72jwyy6yra/comment/51?authorId=1`

**Comment by cyp3rius** [comment]
Fixed in `v3.0.11`

**Comment by NathanBnm** [comment]
@cyp3rius I still have the issue when trying to delete a comment after update.
@Yvres-Vreucheu same for you?

**Comment by Yvres-Vreucheu** [comment]
Yes same for me @NathanBnm

**Comment by Kronos66** [comment]
Hi @Yvres-Vreucheu and @NathanBnm 

Thanks for bringing this to our attention.

I've re-examined the issue you reported, and I'm unable to reproduce it on my end. The comment functionality is working as intended.

To confirm, I performed the following tests:

Added two comments while not logged in.
Added two comments as a logged-in user, using the `Authorization` header for authentication.
Both sets of comments were successfully created.

Here are screenshots showing my results:

![Image](https://github.com/user-attachments/assets/1194bb90-7703-4d9a-8e9d-2546fdf959f0)

![Image](https://github.com/user-attachments/assets/4c8ccf3b-6b8c-4fea-a59a-91d10df512e0)

Could you share more specific steps or a code snippet that demonstrates the problem you're encountering? This would help us understand what might be going wrong.

**Comment by Yvres-Vreucheu** [comment]
Hello @Kronos66  and thanks for your attention.
That's my request 

```
:method  DELETE
:path  /api/comments/api::article.article:nketgecqwk8jsc72jwyy6yra/comment/80?authorId=2
:scheme  https
Accept  application/json, text/plain, */*
Authorization  Bearer xxxxxxx
cache-control  no-cache
content-type  application/json
```

These cookies are also sent with the request so probably there's something annoying with that ? What about you @NathanBnm  ?

__Secure-authjs.callback-url
__Secure-authjs.session-token

Regards

**Comment by Yvres-Vreucheu** [comment]
It works now with v3.1.0 and strapi v5.23.1
